# Generated by Django 5.2.6 on 2025-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('data_tarefa', models.DateTimeField()),
                ('status_tarefa', models.CharField(choices=[('R', 'Realizado'), ('N', 'Não Realizado')], default='N', max_length=1)),
            ],
        ),
    ]
